// card: 300x160 pt web frame at (36, 36), baked
// Generated by packages/web-conformance/indesign (test/indesign-bake.spec.ts).
const pid = JSON.parse(paged.pages())[0].selfId;
paged.createSwatch({"selfId":"Color/wb-f2efe6","name":"Color/wb-f2efe6","space":"RGB","value":[242,239,230],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-1d3557","name":"Color/wb-1d3557","space":"RGB","value":[29,53,87],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-333333","name":"Color/wb-333333","space":"RGB","value":[51,51,51],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-e63946","name":"Color/wb-e63946","space":"RGB","value":[230,57,70],"model":"Process"});
const e1 = paged.insertFrame(pid, [36,36,115.5,336]);
paged.set(e1, "frameFillColor", "Color/wb-f2efe6");
const e2 = paged.insertFrame(pid, [100.5,45,106.5,327]);
paged.set(e2, "frameFillColor", "Color/wb-e63946");
const e3 = paged.insertTextFrame(pid, [44.71875,45,62.8681640625,160.115234375]);
const s3 = JSON.parse(paged.stories()).at(-1).selfId;
paged.insertText(s3, 0, "Quarterly report");
paged.set(`storyRange:${s3}@0..16`, "characterFontSize", 15);
paged.set(`storyRange:${s3}@0..16`, "characterFillColor", "Color/wb-1d3557");
const e4 = paged.insertTextFrame(pid, [68.5546875,45,80.351806640625,187.8465576171875]);
const s4 = JSON.parse(paged.stories()).at(-1).selfId;
paged.insertText(s4, 0, "Revenue grew in every region.");
paged.set(`storyRange:${s4}@0..29`, "characterFontSize", 9.75);
paged.set(`storyRange:${s4}@0..29`, "characterFillColor", "Color/wb-333333");
const e5 = paged.insertTextFrame(pid, [80.5546875,45,92.351806640625,127.3232421875]);
const s5 = JSON.parse(paged.stories()).at(-1).selfId;
paged.insertText(s5, 0, "Costs stayed flat.");
paged.set(`storyRange:${s5}@0..18`, "characterFontSize", 9.75);
paged.set(`storyRange:${s5}@0..18`, "characterFillColor", "Color/wb-333333");
