// shapes: 260x140 pt web frame at (36, 36), baked
// Generated by packages/web-conformance/indesign (test/indesign-bake.spec.ts).
const pid = JSON.parse(paged.pages())[0].selfId;
paged.createSwatch({"selfId":"Color/wb-2a9d8f","name":"Color/wb-2a9d8f","space":"RGB","value":[42,157,143],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-264653","name":"Color/wb-264653","space":"RGB","value":[38,70,83],"model":"Process"});
const e1 = paged.insertPath(pid, [{"anchor":[43.5,52.5],"left":[43.5,52.5],"right":[43.5,47.529437]},{"anchor":[52.5,43.5],"left":[47.529437,43.5],"right":[52.5,43.5]},{"anchor":[279.75,43.5],"left":[279.75,43.5],"right":[284.72057,43.5]},{"anchor":[288.75,52.5],"left":[288.75,47.529437],"right":[288.75,52.5]},{"anchor":[288.75,64.5],"left":[288.75,64.5],"right":[288.75,69.470562]},{"anchor":[279.75,73.5],"left":[284.72057,73.5],"right":[279.75,73.5]},{"anchor":[52.5,73.5],"left":[52.5,73.5],"right":[47.529437,73.5]},{"anchor":[43.5,64.5],"left":[43.5,69.470562],"right":[43.5,64.5]}], false, false);
paged.set(e1, "frameFillColor", "Color/wb-2a9d8f");
const e2 = paged.insertPath(pid, [{"anchor":[43.5,99.75],"left":[43.5,99.75],"right":[43.5,89.39466]},{"anchor":[62.25,81],"left":[51.894661,81],"right":[62.25,81]},{"anchor":[62.25,81],"left":[62.25,81],"right":[72.60534,81]},{"anchor":[81,99.75],"left":[81,89.39466],"right":[81,99.75]},{"anchor":[81,99.75],"left":[81,99.75],"right":[81,110.10534]},{"anchor":[62.25,118.5],"left":[72.60534,118.5],"right":[62.25,118.5]},{"anchor":[62.25,118.5],"left":[62.25,118.5],"right":[51.894661,118.5]},{"anchor":[43.5,99.75],"left":[43.5,110.10534],"right":[43.5,99.75]}], false, false);
paged.set(e2, "frameFillColor", "Color/wb-264653");
