// shapes: 260x140 pt web frame at (36, 36), baked
// Generated by packages/web-conformance/indesign (test/indesign-bake.spec.ts).
const pid = JSON.parse(paged.pages())[0].selfId;
paged.createSwatch({"selfId":"Color/wb-2a9d8f","name":"Color/wb-2a9d8f","space":"RGB","value":[42,157,143],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-264653","name":"Color/wb-264653","space":"RGB","value":[38,70,83],"model":"Process"});
const e1 = paged.insertFrame(pid, [43.5,43.5,73.5,288.75]);
paged.set(e1, "frameFillColor", "Color/wb-2a9d8f");
paged.set(e1, "frameCornerOptionTopLeft", "RoundedCorner");
paged.set(e1, "frameCornerRadiusTopLeft", 9);
paged.set(e1, "frameCornerOptionTopRight", "RoundedCorner");
paged.set(e1, "frameCornerRadiusTopRight", 9);
paged.set(e1, "frameCornerOptionBottomLeft", "RoundedCorner");
paged.set(e1, "frameCornerRadiusBottomLeft", 9);
paged.set(e1, "frameCornerOptionBottomRight", "RoundedCorner");
paged.set(e1, "frameCornerRadiusBottomRight", 9);
const e2 = paged.insertFrame(pid, [81,43.5,118.5,81]);
paged.set(e2, "frameFillColor", "Color/wb-264653");
paged.set(e2, "frameCornerOptionTopLeft", "RoundedCorner");
paged.set(e2, "frameCornerRadiusTopLeft", 18.75);
paged.set(e2, "frameCornerOptionTopRight", "RoundedCorner");
paged.set(e2, "frameCornerRadiusTopRight", 18.75);
paged.set(e2, "frameCornerOptionBottomLeft", "RoundedCorner");
paged.set(e2, "frameCornerRadiusBottomLeft", 18.75);
paged.set(e2, "frameCornerOptionBottomRight", "RoundedCorner");
paged.set(e2, "frameCornerRadiusBottomRight", 18.75);
