// swatches: 240x120 pt web frame at (36, 36), baked
// Generated by packages/web-conformance/indesign (test/indesign-bake.spec.ts).
const pid = JSON.parse(paged.pages())[0].selfId;
paged.createSwatch({"selfId":"Color/wb-ff0000","name":"Color/wb-ff0000","space":"RGB","value":[255,0,0],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-00a050","name":"Color/wb-00a050","space":"RGB","value":[0,160,80],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-0040ff","name":"Color/wb-0040ff","space":"RGB","value":[0,64,255],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-ffcc00","name":"Color/wb-ffcc00","space":"RGB","value":[255,204,0],"model":"Process"});
paged.createSwatch({"selfId":"Color/wb-000000","name":"Color/wb-000000","space":"RGB","value":[0,0,0],"model":"Process"});
const e1 = paged.insertFrame(pid, [36,36,66,66]);
paged.set(e1, "frameFillColor", "Color/wb-ff0000");
const e2 = paged.insertFrame(pid, [36,72,66,102]);
paged.set(e2, "frameFillColor", "Color/wb-00a050");
const e3 = paged.insertFrame(pid, [36,108,66,138]);
paged.set(e3, "frameFillColor", "Color/wb-0040ff");
const e4 = paged.insertFrame(pid, [36,144,66,174]);
paged.set(e4, "frameFillColor", "Color/wb-ffcc00");
const e5 = paged.insertTextFrame(pid, [72.28125,36,83.1708984375,158.2783203125]);
const s5 = JSON.parse(paged.stories()).at(-1).selfId;
paged.insertText(s5, 0, "Four swatches, one caption.");
paged.set(`storyRange:${s5}@0..27`, "characterFontSize", 9);
paged.set(`storyRange:${s5}@0..27`, "characterFillColor", "Color/wb-000000");
paged.set(`storyRange:${s5}@0..27`, "characterFontFamily", "Inter");
